steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/agnet-workspace-api:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/agnet-workspace-api:latest', '.']

  # Step 2: Push the image with commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/agnet-workspace-api:$SHORT_SHA']

  # Step 3: Push the latest image tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/agnet-workspace-api:latest']

  # Step 4: Update GKE deployment to the new image
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/agnet-workspace-api'
      - 'agnet-workspace-api=gcr.io/$PROJECT_ID/agnet-workspace-api:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=agent-workspace-cluster'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/agnet-workspace-api:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/agnet-workspace-api:latest'
